### ISSUE TITLE
Should the iex buffer be surfaced when you send a command to it?

### ISSUE THREAD

**Issue by pragdave** [tonini/alchemist.el#104]
It my iex buffer is hidden, and I use something like C-c a i r, the region is evaluated, but we don't see it because the iex buffer remains hidden.

This is possibly the way it is supposed to be. :)

**Comment by tonini** [comment]
Hi @pragdave 

Thanks for reporting this behavior.

I think this is not the way it suppose to work, I will fix that. ;-)

If you get some spare time, you might have a look at Alchemist v1.0 beta, with the new Alchemist-Server behind it's an amazing experience to work with things like documentation lookup, completion, jump to definition or code inline evaluation.

https://github.com/tonini/alchemist.el/pull/102

Cheers,

Samuel

**Comment by pragdave** [comment]
I'm using the beta right now. Very impressive. In fact, I'll be using it when I give a talk tomorrow.

Quick question—how do I trigger completion (the equivalent of tab) in alchemist-iex?

**Comment by tonini** [comment]
@pragdave For completion we need company-mode and I just set `TAB` to the `company-complete` function inside the IEx buffer because people like to bind `TAB` to different things like custom functions which handles indentation too etc.

Here you can see an example of a function which handles indention and completion through one function http://www.emacswiki.org/emacs/CompanyMode#toc9

For myself I bind it to <kbd>C-_</kbd> but your free to bind it to what you want. So we have not set any default key for completion so far. 

Personal binding:
`(global-set-key (kbd "C-_") 'company-complete)`

The `company-mode` the package Alchemist uses to hang in the alchemist-backend into the completion functionality, has some configuration variables which you can setup.

For example my personal setup is:

```el
(setq company-idle-delay 0.1)
(setq company-tooltip-limit 10)
(setq company-minimum-prefix-length 2)
(setq company-tooltip-flip-when-above t)
```

I really appreciate it and happy you like Alchemist v1.0 so far :) Have a good talk tomorrow :+1:

**Comment by tonini** [comment]
Hi @pragdave 

I realized that this issue was about something other than the completion stuff, so I try to respond to the first question you had. :-)

> It my iex buffer is hidden, and I use something like C-c a i r, the region is evaluated, but we don't see it because the iex buffer remains hidden.

Currently thats how it works:

The function `alchemist-iex-send-region` just the marked region to the IEx process.
On the other hand, the function `alchemist-iex-send-region-and-go` sends the marked region to the inferior IEx process and jump to the buffer.

But you might be correct, we should at least display the IEX process buffer if you use `alchemist-iex-send-region`.

I will update that asap.

**Comment by tonini** [comment]
Hi @pragdave 

I had a look at some other `inf-mode` like for `ruby`, `haskell`, `clojure` etc and now I remember why I implemented it the way it currently works.

If you would like that the `IEx` buffer will popup after you send an expression, you need to use the `-and-go` function implementations like `alchemist-iex-send-region-and-go`.

Could you work with that? :)

**Comment by pragdave** [comment]
I suppose. I just can't think of a case where I wouldn't want it to.... :)
