### ISSUE TITLE
show alchemist-goto-list-symbol-definitions in ido buffer ?

### ISSUE THREAD

**Issue by rogergl** [tonini/alchemist.el#173]
Is it possible to use the result from e.g. alchemist-goto-list-symbol-definitions  in an ido buffer ?  Right now I have to press C-,., 2 times tab and then select the function.

**Comment by tonini** [comment]
@rogergl I think I don't understand exactly what you mean. If you use something like `(ido-everywhere 1)` already, then it uses the `ido-completing-read` instead the `completing-read`.

>  Right now I have to press C-,., 2 times tab and then select the function.

This sounds like something with your Emacs config is not right, the `alchemist-goto-list-symbol-definitions` function simple delivers the matches via the `completing-read`. If you use something like `helm` or `ido-vertical-mode` it looks like the following: 

![](http://i.imgur.com/YycnI7b.gif)

**Comment by rogergl** [comment]
Thats not how it is working here. I tested with a clean .emacs filed, removed all the packages and just installed alchemist and enabled ido mode.

**Comment by tonini** [comment]
How it works then for you? I need a detailed description how it works and
looks in the end, maybe screenshots or animated GIF's that would be great!
:)

Roger Gilliar <notifications@github.com> schrieb am Di., 6. Okt. 2015 08:08:

**Comment by rogergl** [comment]
![Image of Selection](http://www.gfycat.com/PessimisticImpracticalCanine)

**Comment by tonini** [comment]
@rogergl Ah I see.

If you would like to have the same behavior as in the GIF above you need to do the following:

* `(ido-everywhere 1)`
* install the package [ido-vertical-mode](https://github.com/creichert/ido-vertical-mode.el) or implement the vertical listing by [yourself](http://emacswiki.org/emacs/InteractivelyDoThings#toc23)

Then it should work as expected.

Most of the Alchemist users work with `helm` that's the reason I did't realize this situation. But maybe I need to think about to create a specific buffer with the listing by itself, so that it is a bit more independent.

**Comment by rogergl** [comment]
ido-vertical mode was installed and  ido-everywhere  was enabled.

**Comment by rogergl** [comment]
It is almost working if helm is installed. The only problem is that the helm window isn't displayed below the source.  But that is probably just a missing helm config.
![sc](https://cloud.githubusercontent.com/assets/98088/10302018/8145ae98-6c08-11e5-9142-4c8905c9be06.png)

**Comment by tonini** [comment]
Yes you need to setup the `helm ` buffer appearance in the config.

About the `ido` part, did you setup it correct as mentioned in the readme? 

```el
(require 'ido-vertical-mode)
(ido-mode 1)
(ido-vertical-mode 1)
```

Sorry for being that fussy, I just wondering what it can be. :smile:

**Comment by rogergl** [comment]
Yes that's how i configured ido mode.

**Comment by tonini** [comment]
@rogergl Ok, then it might be an Emacs setup problem, because all what `alchemist-goto-list-symbol-definitions` does in the end is call `completing-read`. I can't help you with my `ido-mode` knowledge at this point, you need to have a look at the [EmacsWiki](https://www.google.ch/search?q=emacswiki+ido-mode&oq=emacswiki+ido-mode&aqs=chrome..69i57j69i65l3j69i60l2.2423j0j7&sourceid=chrome&es_sm=91&ie=UTF-8) ido-mode resource or ask in the Freenode #emacs channel why `(ido-everywhere 1)` is not working.

**Comment by rogergl** [comment]
Thanks for the help, but I think I'll continue using helm.

**Comment by tonini** [comment]
You're welcome.
