### ISSUE TITLE
Autocomplete takes precedence over `end` keyword

### ISSUE THREAD

**Issue by lexmag** [tonini/alchemist.el#181]
As you see on the following screenshot it's natural to type \<tab\> in order to make indentation but currently it turns into autocompletion.

<img width="184" alt="screen shot 2015-10-21 at 21 21 30" src="https://cloud.githubusercontent.com/assets/248290/10647645/d338612c-7839-11e5-94d0-690dd5b2e48d.png">

It's getting really annoying as `cond`, `case`, `def`, etc. (pretty much everything) ends with `end`.

**Comment by tonini** [comment]
Hi @lexmag 

Alchemist use [company-mode](http://company-mode.github.io/) library to deliver the completion candidates to the `GUI`. The problem you're experienced about that things like `ends_with?` will always try to complete it's because your `company-idle-delay` time is set to `0.3` currently and after that time it tries to complete what it has available, in this case `ends_with?`.

I don't like the autocompletion all the time so I increase the `company-idle-delay` time to about `3` and then use a custom keybinding to explicit call `company-complete` for get completion candidates.

You can bind it to `TAB` for example, there are some Emacs Lisp function example available which first try to indent in context of the current major mode and afterwards try to complete.

Here you find an interesting discussion about how `TAB` should/could behave https://github.com/company-mode/company-mode/issues/94

PS: I know that it would be nice if `elixir-mode` or `alchemist` could handle the context and don't try to complete on things like `do` or `end`, but for that you need a really clever parser which you don't write in just an evening. :)

There are discussions about creating an AST graph with the `alchemist-server` and get to the next level, but that things we look at it with version 2.0

**Comment by tonini** [comment]
It looks like I found an issue about the case you reported.

Besides all I said, there is the case which removes the current prefix from the completion candidates list.
Thats why it overwrites fro examples your `end` into `ends_with?` and that's really a bug. :+1: 

Thanks a lot for this report, I will fix it as soon as possible.

**Comment by lexmag** [comment]
Hey @tonini, thank you for such an informative reply. I'll try to adjust my company-mode settings.

> I know that it would be nice if elixir-mode or alchemist could handle the context and don't try to complete on things like do or end, but for that you need a really clever parser which you don't write in just an evening. :)

Let me know if you need any help on this. :smile: 

> There are discussions about creating an AST graph with the alchemist-server and get to the next level, but that things we look at it with version 2.0

Is there any open issues about it?

**Comment by tonini** [comment]
Morning @lexmag 

> Let me know if you need any help on this. 

Not so far, I will tag you on the [Alchemist-Server](https://github.com/tonini/alchemist-server) when I open an issue about that theme.

I had a look at `company-mode` and the behavior of Alchemist's completion in situations where you just have one candidate, like you mentioned above with `[end]s_with?`.

I tried to add the current prefix (in that case `end`) to the completion candidate list when there is no more than one available candidate.

For example.

![one candidate prefix](http://i.imgur.com/vRlplTh.png)

What I also did is bind `TAB` inside the completion map to select which in the case when you don't want any completion selection, just takes the first candidate from the list (the `end` in our situation).

```lisp
(define-key company-active-map (kbd "TAB") 'company-complete-selection)
```

After that first `TAB` for selection, just hit another one for the indentation.

What do you think about that behavior?

**Comment by lexmag** [comment]
Morning @tonini, that sounds great, I'm eager to try it in a real workflow. :smile:
Thank you for fixing this.

**Comment by tonini** [comment]
@lexmag It's now available on [master](https://github.com/tonini/alchemist.el/commit/6bce8673693f79d7b2011d386e39347d32d8132e) 

If you want to update it with `list-packages` you need to wait until [MELPA](https://melpa.org/#/) built the latest package from master.

**Comment by tonini** [comment]
@lexmag did you had the time to test it?

**Comment by lexmag** [comment]
@tonini yes, I've spent one working day with this change, and, in overall, it feels like a better experience then was previously.

**Comment by tonini** [comment]
great! :)

Btw, maybe you should have a look at a few `company-mode` custom variables which maybe will increase your workflow even more. For example `company-minimum-prefix-length` I have it on `4` so I won't get any completion on things like `do` and `end` expect when I call `company-complete` explicit.

There are a few other variables you might should have a look at it.

I close this issue for now, just ping me on IRC if you have further questions.
