### ISSUE TITLE
Auto-Completion not working

### ISSUE THREAD

**Issue by evanson** [tonini/alchemist.el#189]
Hi,

I installed alchemist manually and auto-completion is not working.  

Am also getting this error in the *alchemist-server* buffer: 
** (SyntaxError) /home/evanson/.emacs.d/vendor/alchemist.el/alchemist-server/lib/api/docl.exs:30: an expression is required on the right side of ->. Syntax error after: '->'
    (elixir) lib/code.ex:363: Code.require_file/2
    /home/evanson/.emacs.d/vendor/alchemist.el/alchemist-server/lib/server.exs:2: (file)
    (elixir) lib/code.ex:363: Code.require_file/2

Process alchemist-server exited abnormally with code 1

**Comment by lexmag** [comment]
I assume you are running on Elixir master, as since next version the `->` with an empty right-hand side will throw an error.
The following line https://github.com/tonini/alchemist.el/blob/master/alchemist-server/lib/api/docl.exs#L30 triggers it to happen.

**Comment by evanson** [comment]
Yes indeed, am running on master.

**Comment by tonini** [comment]
Thanks @evanson for the report and @lexmag for the information about the changes on master. I' ll will update asap. 

Cheers

**Comment by tonini** [comment]
Good morning @evanson 

The issue is fixed on master now https://github.com/tonini/alchemist.el/commit/a812494b6c3d18c2a9ed980f3bc1414b5d509862

You might want to wait until [MELPA](https://melpa.org/) build the latest Alchemist package from the master branch if you using `M-x package-install` (Emacs package manager `package.el`) to install Alchemist. Otherwise just pull the master branch and you should  be good to go.

Thanks

**Comment by evanson** [comment]
Morning @tonini,

Thanks! It's now working. 

Onto some elixir hacking now!
