### ISSUE TITLE
quickhelp vertical shift

### ISSUE THREAD

**Issue by gaydenko** [tonini/alchemist.el#256]
Hi! 

Please. look at the https://github.com/expez/company-quickhelp/issues/49

Also I have found elixir qiuckhelp always starts form the second row in the tooltip window, while, say, elisp quckhelp starts from the first. Can these two observation be related to each other ant to, probably, the way quickhelp API is used by alchemist (say, indexing or something else)? Say, some unexpected text vertical shift down one row.

P.S. Thanks for the alchemist el!

**Comment by tonini** [comment]
Hi @gaydenko 

>>  ..the way quickhelp API is used by alchemist....

First, Alchemist doesn't uses `company-quickhelp` at all. The`company-quickhelp` uses the Alchemist related company doc functionality. It's important to say that because people getting to confused lately where the responsability about issue could be. 😏 

Second, to your issue about where the tooltip windows starts. I don't know, honestly this is not an Alchemist thing at all, it's all about `company` or `company-quickhelp`. What you could do is checking out the latest Alchemist master and check it again. I tweaked some things about removing the search completion prefix out of the candidate list.

Cheers

**Comment by gaydenko** [comment]
@tonini , hi!

Have tried  7512305 and got the same result (that is shifting). My idea was company/company-quickhelp behave as expected because the issue doesn't take place with other (elisp) language.

As far as the issue isn't alchemist related, closing it.
