### ISSUE TITLE
Company mode issue with keywords < 3 characters long

### ISSUE THREAD

**Issue by pragdave** [tonini/alchemist.el#286]
See this video: https://www.youtube.com/watch?v=CLiRhkRHEo8

If you enter "do" at the end of a line, and there are names that start "doxxx" in the buffer, the first completion is added when you hit return (the "do" becomes "doxxx")

Dave

**Comment by tonini** [comment]
Hi @pragdave 

Thanks for your feedback about this behavior.
The case you explaining is kind of known and I already started to think about to hardcore the handling about the completion issue with keywords like "do". But I'm still not sure what would be a proper solutation to handle this.

What I would recommend at this point is, that you setup your company mode variable "company-minimum-prefix-length" to 3 instead of 2. With this setup the completion will not start in cases like you explained, until you hit a third character.

Thanks the report and thanks for your patience.

**Comment by pragdave** [comment]
Thanks for the reply.

I understand your pain—I spend 30 fruitless minutes trying to understand
company-mode before giving up.

Thanks for everything you do.


Dave

**Comment by tonini** [comment]
You're welcome and thanks for your feedback. :+1:
