### ISSUE TITLE
Discuss: running project while "goto" and "complete"

### ISSUE THREAD

**Issue by X4lldux** [tonini/alchemist.el#42]
Does those to features need to run the entire project? Sometimes apps do some kind of cleaning up and resetting some data (clearing logs, metric counters, etc) when are started, so developers run them in strict conditions. Or simply take a while to initiate. But alchemist starts them whenever it needs.
I've noticed '--no-compile' option when alchemist runs mix run and I think there should be also '--no-start' - what will it break?

**Comment by tonini** [comment]
@X4lldux Thanks for the feedback, I will have a look into it, maybe a good idea to prevent the application start.

**Comment by X4lldux** [comment]
What did it break?

**Comment by koudelka** [comment]
I'd love to hear more discussion on this. Starting apps for code completion seems like it might be a bad idea.

**Comment by tonini** [comment]
We're working on Alchemist v1.0 and this will be all fixed when done.

Thanks for your patience and using Alchemist. :heart:

**Comment by rranelli** [comment]
Maybe looking at projects like `Ensime` that provide badass completion could provide some insight.

**Comment by tonini** [comment]
Hi,

This issue will be fixed with Alchemist v1.0.0 which will be released in the upcoming weeks.

Alchemist v1.0 will go a different approach and bring kind of a server for each project. This will improve stability and performance. It also won't affect the project you working on in any away. 

For example, here is just a little gif where you can see the new doc lookup performance in action:

![Alchemist v1.0 DOC lookup](http://i.imgur.com/Vrx8mtX.gif)

Thanks for the patience and supporting Alchemist :heart:

**Comment by X4lldux** [comment]
Wow! Now that's amazing :heart:
Will it be affected by run time errors in modules?

**Comment by tonini** [comment]
> Will it be affected by run time errors in modules?

Not at all, the application will not be started in any kind of situation.

**Comment by tonini** [comment]
@X4lldux could you please test Alchemist v1.0? I think we could close this issue after that :+1:

**Comment by X4lldux** [comment]
Sorry for late response!
It works grate! And I'm impressed that code which is outside `defmodule` block is not executed by the server either - you rock!
