### ISSUE TITLE
Completion breaks with company-yasnippet

### ISSUE THREAD

**Issue by edubkendo** [tonini/alchemist.el#67]
When I add company-yasnippet to my company backends, alchemist completions break but I get Elixir snippets. If I then add alchemist back into the the company backends , if I add it after adding company-yasnippet, it starts working and yasnippets quit getting loaded as a backend, and vice-versa. Basically, I'd like to have both show up in my list of completions, but I can't figure out how.

**Comment by jtmoulia** [comment]
Hey @edubkendo, have you tried grouping the backends?

Something like:
```elisp
(add-to-list 'company-backends '(company-alchemist company-yasnippet))
```

Referencing #66 -- maybe this will help.

**Comment by edubkendo** [comment]
Ah so it looks like what I'm seeing is the result of how company works to some extent, and the fact that these two modes aren't returning nil when they don't have a result. At least that's what I gather from reading #66 .

**Comment by jtmoulia** [comment]
Yup, but you should be able to group the backends, which is what I was going for in the code snippet above. It's not a general solution to #66, but I think it'll work for you since you want to merge the results from 2 backends.

From the doc for the `company-backends` variable:

> The completions from back-ends in a group are merged (but only from those that return the same `prefix').

One potential issue is that `company-alchemist` and `company-yasnippet` use different functions to get the prefix, so they might not return the same prefix. But, I think that as long as the cursor is at the end of a "word" you should be fine.

Sorry, haven't had a chance to test this!

**Comment by edubkendo** [comment]
unfortunately, when I try that, I only see yasnippet results, alchemists stop working.

**Comment by edubkendo** [comment]
whoops sorry, take that back. it works great the snippet just needs a tweak:

```elisp
(add-to-list 'company-backends '(alchemist-company company-yasnippet))
```

**Comment by jtmoulia** [comment]
Ah, my bad -- good to hear it works!
